version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: clean_postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME:-clean_db}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - clean_net
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER:-postgres}']
      interval: 5s
      timeout: 5s
      retries: 5

  loki:
    image: grafana/loki:2.9.3
    container_name: clean_loki
    ports:
      - '3100:3100'
    volumes:
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - clean_net

  prometheus:
    image: prom/prometheus:v2.48.1
    container_name: clean_prometheus
    ports:
      - '${PROMETHEUS_PORT:-9090}:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - clean_net

  grafana:
    image: grafana/grafana:10.2.3
    container_name: clean_grafana
    ports:
      - '${GRAFANA_PORT:-3001}:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - loki
      - prometheus
    networks:
      - clean_net

volumes:
  postgres_data:
  loki_data:
  prometheus_data:
  grafana_data:

networks:
  clean_net:
